<?php
    require_once("../../classes/dbUtils.php");

    //add comment, reload info from database, then display
    if (isset($_GET['newComment']) && $_GET['newComment'] != '') {
        $requestedFilePath = $_GET['filePath'];
        $commentParentId = $_GET['parentCommentId'];
        $commentText = urldecode($_GET['newComment']);

        DBUtils::addCommentToDataBase($commentParentId, $requestedFilePath, $commentText);
        require("../../webView/autogeneratedElements/loadPortfolioFromDB.php");//reloaded
        echo $portfolio->generateHTMLCommentsForPath($requestedFilePath);
    }
?>
