<html>
    <head>
        <title>Bloopa</title>
        <link rel="stylesheet" type="text/css" href="/Assignment3.2/webView/styles/copiedStyles.css" media="screen">
        <script src="https://code.jquery.com/jquery-3.0.0-alpha1.js"></script>
        
        <?php
            require_once("../../classes/utils.php");
            require_once("../../classes/dbUtils.php");
            require("../../webView/autogeneratedElements/loadPortfolioFromDB.php");
            $tab = Utils::tab();
            $requestedRevision = $_GET['revision'];
        ?>
    </head>
    
    <body>
        <?php
            if($portfolio->commitExists($requestedRevision)){
                echo     "<div class='navLink'>
                                <a class='navLink' href='/Assignment3.2/webView/pages/index.php'>Home</a>
                                {$tab}{$tab} Revision: {$requestedRevision}
                         </div>
                         <div id='content'>{$portfolio->generateHTMLfromCommitMods($requestedRevision)}</div>";
            }
        
            else{
                 echo "    <div class='navLink'>
                                <a class='navLink' href='/Assignment3.2/webView/pages/index.php'>Home</a>
                                {$tab}{$tab} Error: commit not in portfolio
                          </div>";
            }
            
        ?>


    </body>
</html>