<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Bloopa</title>
    <link rel="stylesheet" type="text/css" href="/Assignment3.2/webView/styles/copiedStyles.css" media="screen">
    <!--<link rel="stylesheet" type="text/css" href="/Assignment3.2/webView/styles/tmestyle.css" media="screen">!-->
    <?php
        include('../../classes/utils.php');
        $tab = Utils::tab();
    ?>
</head>

<body>
    <div class='navLink'>
                        <a class='navLink' href='/Assignment3.2/webView/pages/index.php'>Home</a>
                        <?php echo("{$tab}{$tab}CS 242 Portfolio"); ?>
    </div>
    <div id="content">
        <div class="tree">
            <?php
                require_once("../../webView/autogeneratedElements/loadPortfolioFromDB.php");
                echo $portfolio->generateHTMLString();
            ?>
        </div>
    </div>

